config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get 'home/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pin.rb
class Pin < ApplicationRecord
    belongs_to :user
    has_one_attached :pin_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  # will get "activestorage Cannot generate URL for using Disk service" if this is absent
  include ActiveStorage::SetCurrent

  before_action :set_pin, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index, show ]
  before_action :correct_user, only: %i[ edit, update, destroy ]

  # GET /pins or /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1 or /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins or /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    # respond_to do |format|
      if @pin.save
        # format.html { redirect_to @pin, notice: "Pin was successfully created." }
        # format.json { render :show, status: :created, location: @pin }
        redirect_to @pin, notice: "Pin was successfully created."
      else
        # format.html { render :new, status: :unprocessable_entity }
        # format.json { render json: @pin.errors, status: :unprocessable_entity }
        render action: "new"
      end
    #end
  end

  # PATCH/PUT /pins/1 or /pins/1.json
  def update
    #respond_to do |format|
      if @pin.update(pin_params)
        # format.html { redirect_to @pin, notice: "Pin was successfully updated.", status: :see_other }
        # format.json { render :show, status: :ok, location: @pin }
        redirect_to @pin, notice: "Pin was successfully updated."
      else
        # format.html { render :edit, status: :unprocessable_entity }
        # format.json { render json: @pin.errors, status: :unprocessable_entity }
        render action: "edit"
      end
    #end
  end

  # DELETE /pins/1 or /pins/1.json
  def destroy
    @pin.destroy

    #respond_to do |format|
    #  format.html { redirect_to pins_path, notice: "Pin was successfully destroyed.", status: :see_other }
    #  format.json { head :no_content }
    #end
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pin_params
      params.require(:pin).permit(:description, :pin_image)
    end
end

def correct_user
  @pin = current_user.pins.find_by(id: params[:id])
  redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <%= link_to "Pinterested", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "About Me", home_about_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to "Add Pin", new_pin_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "List Pins", pins_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Logout", destroy_user_session_path, class: "nav-link", data: { "turbo-method": :delete } %>
            </li>
            <li class="nav-item">
                <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Join", new_user_registration_path, class: "nav-link" %>
            </li>
        <% end %>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Me!</h1>
<p>My name is James Elwell and I'm building a Pinterested website.</p>

app/views/home/index.html.erb
<div class="mt-4 p-5 bg-light rounded">
    <h1>Welcome to my Pinterested App!</h1>
    <p>Find me in app/views/home/index.html.erb</p>
    <% if user_signed_in? %>
        <%= link_to "Logout", destroy_user_session_path, class: "btn btn-primary", data: { "turbo-method": :delete } %>
        <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-secondary" %>
        <%= link_to "List Pins", pins_path, class: "btn btn-secondary" %>
    <% else %>
        <%= link_to "Login", new_user_session_path, class: "btn btn-secondary" %>
        <%= link_to "Join", new_user_registration_path, class: "btn btn-primary" %>
    <% end %>    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterested</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "home/header" %>
    <div class="container">
      <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class:"alert alert-info") %>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin, html: { multipart: true} ) do |form| %>
  <% if pin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
        <% pin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class: "form-control", style: "width:500px" %>
  </div>

  <div class="form-group">
    <%= form.label :pin_image, style: "display: block" %>
    <%= form.file_field :pin_image, class: "form-control" %>
  </div>

  <div>
    <%= form.submit "Submit", class: "btn btn-primary mt-2" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div id="<%= dom_id pin %>">
  <p>
    <%= image_tag pin.pin_image.variant(resize_to_limit: [300, 300]).processed %>
    <br/>
    <strong>Description:</strong>
    <%= pin.description %>
  </p>

</div>

app/views/pins/edit.html.erb
<div class="card mt-3">
  <div class="card-header">
    <h1>Editing pin</h1>
  </div>
  <div class="card-body">
    <%= render "form", pin: @pin %>
  </div>
  <div class="card-footer">
    <%= link_to "Show this pin", @pin %> |
    <%= link_to "Back to pins", pins_path %>
  </div>   
</div>

app/views/pins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Listing Pins</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @pins.each do |pin| %>
      <tr>
        <td><%= image_tag pin.pin_image.variant(resize_to_limit: [75, 75]).processed %></td>
        <td><%= pin.description %></td>
        <td><%= link_to "Show", pin %></td>
        <td><%= link_to "Edit", edit_pin_path(pin) %></td>
        <td><%= link_to "Destroy", pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New pin", new_pin_path %>

app/views/pins/new.html.erb
<div class="card mt-3">
  <div class="card-header">
    <h1>New pin</h1>
  </div>
  <div class="card-body">
    <%= render "form", pin: @pin %>
  </div>
  <div class="card-footer">
    <%= link_to "Back to pins", pins_path %>
  </div>   
</div>

app/views/pins/show.html.erb
<%= render @pin %>

<div>
  <%= link_to "Edit this pin", edit_pin_path(@pin) %> |
  <%= link_to "Back to pins", pins_path %>

  <%= button_to "Destroy this pin", @pin, method: :delete %>
</div>